#!/opt/conda/bin/python
import git
from rebar import storing

commit = str(git.Repo().head.commit)[:6]
run = storing.runs().iloc[-1]['run_name']
print(f'[[Boardlaw#Ref]] (`{commit}`):')
print(f'[[Boardlaw#Runs]] (`{commit}`, `{run}`):')
